import assert from "node:assert/strict";
import { csvDealsRepository } from "../src/repositories/deals/csv-deals-repository";
import { createCrmStore } from "../src/repositories/sqlite/crm-store";
import { getCrmSnapshot } from "../src/services/crm/crm-service";
import { dashboardMetrics, PRIORITIZED_SCORE_CUTOFF } from "../src/services/dashboard/dashboard-metrics";
import { emptyPriorityFilters, rankTopFive } from "../src/services/priorities/rank-top-five";

const store = createCrmStore(":memory:");
const snapshot = getCrmSnapshot(await csvDealsRepository.list(), store);
store.close();
const scoresBefore = JSON.stringify(snapshot.scores), tiersBefore = JSON.stringify(snapshot.tiers);
const base = dashboardMetrics(snapshot, emptyPriorityFilters, "all", new Date("2026-09-25T12:00:00Z"));
assert.equal(base.open.count, 2089);
assert.equal(base.topFive.eligibleCount, 2089);
assert.deepEqual(base.topFive.items.map((deal) => deal.id), rankTopFive(snapshot.deals,snapshot.scores,snapshot.tiers,snapshot.dealTags).items.map((deal) => deal.id));
assert.equal(base.stages.reduce((sum, stage) => sum + stage.count, 0), base.open.count);
assert.equal(base.actions.reduce((sum, action) => sum + action.count, 0), base.open.count);
assert.equal(base.tiers.reduce((sum, tier) => sum + tier.count, 0), base.open.count);
assert.equal(base.evidence.reduce((sum, evidence) => sum + evidence.count, 0), base.open.count);
assert.equal(base.prioritized.count, snapshot.deals.filter((deal) => snapshot.scores[deal.id]?.priorityScore >= PRIORITIZED_SCORE_CUTOFF).length);
assert.equal(base.tasks.overdue <= base.tasks.pending, true);
const agent = snapshot.deals.find((deal) => snapshot.scores[deal.id])!.agent;
const filtered = dashboardMetrics(snapshot, { ...emptyPriorityFilters, agent }, "month", new Date("2026-09-25T12:00:00Z"));
assert.equal(filtered.open.count, snapshot.deals.filter((deal) => snapshot.scores[deal.id] && deal.agent === agent).length);
assert.equal(filtered.stages.reduce((sum, stage) => sum + stage.count, 0), filtered.open.count);
assert.equal(filtered.topFive.eligibleCount, filtered.open.count);
assert.equal(filtered.tasks.completed <= base.tasks.completed, true);
const template = snapshot.deals.find((deal) => snapshot.scores[deal.id])!;
const customDeal = { ...template, id: "ARENA-TEST-STAGE", stageId: "custom-stage" };
const custom = { ...snapshot, deals: [...snapshot.deals, customDeal], scores: { ...snapshot.scores, [customDeal.id]: snapshot.scores[template.id] }, tiers: { ...snapshot.tiers, [customDeal.id]: snapshot.tiers[template.id] }, stages: [...snapshot.stages, { id: "custom-stage", funnelId: template.funnelId, name: "Etapa especial", order: 10, category: "OPEN" as const, isDefault: false, active: true, createdAt: "2026-09-25T00:00:00Z" }] };
assert.equal(dashboardMetrics(custom, emptyPriorityFilters, "all").stages.find((stage) => stage.label === "Etapa especial")?.count, 1);
assert.equal(JSON.stringify(snapshot.scores), scoresBefore);
assert.equal(JSON.stringify(snapshot.tiers), tiersBefore);
console.log("Dashboard PASS: cards, filtros, etapas personalizadas, ações, tiers, evidência, tarefas e Top 5 compartilhado.");
