import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import { csvDealsRepository } from "../src/repositories/deals/csv-deals-repository";
import { createCrmStore } from "../src/repositories/sqlite/crm-store";
import { createEmailRepository } from "../src/repositories/email/sqlite-email-repository";
import { getCrmSnapshot } from "../src/services/crm/crm-service";
import { priorityDigest } from "../src/services/email/priority-digest";
import { nextRunAt } from "../src/services/email/schedule-time";
import { resendConfigured, type EmailAdapter, type EmailMessage } from "../src/services/email/resend-adapter";
import { runDueEmailSchedules, saveEmailSchedule, sendManualDigest, setEmailScheduleEnabled } from "../src/services/email/email-service";
import { emptyPriorityFilters, rankTopFive } from "../src/services/priorities/rank-top-five";

const temporary = mkdtempSync(path.join(os.tmpdir(), "arena-email-"));
const dbPath = path.join(temporary, "test.sqlite");
try {
  const crm = createCrmStore(":memory:");
  const snapshot = getCrmSnapshot(await csvDealsRepository.list(), crm);
  crm.close();
  const scoresBefore = JSON.stringify(snapshot.scores), tiersBefore = JSON.stringify(snapshot.tiers);
  const scope = { ...emptyPriorityFilters, agent: snapshot.deals.find((deal) => snapshot.scores[deal.id])!.agent };
  const digest = priorityDigest(snapshot, scope);
  assert.deepEqual(digest.items.map((item) => item.id), rankTopFive(snapshot.deals,snapshot.scores,snapshot.tiers,snapshot.dealTags,scope).items.map((deal) => deal.id));
  assert.ok(!digest.text.includes("MEDIUM") && !digest.text.includes("LOW"));
  assert.ok(digest.html.includes("Suas prioridades"));
  assert.equal(nextRunAt({ frequency: "daily", sendTime: "08:00", weekday: null, dayOfMonth: null }, new Date("2026-09-25T10:00:00Z")), "2026-09-25T11:00:00.000Z");
  assert.equal(nextRunAt({ frequency: "weekly", sendTime: "08:00", weekday: 1, dayOfMonth: null }, new Date("2026-09-25T10:00:00Z")), "2026-09-28T11:00:00.000Z");
  assert.equal(nextRunAt({ frequency: "monthly", sendTime: "08:00", weekday: null, dayOfMonth: 31 }, new Date("2027-02-01T00:00:00Z")), "2027-02-28T11:00:00.000Z");
  const sent: EmailMessage[] = [];
  const adapter: EmailAdapter = { async send(message) { sent.push(message); return `mock-${sent.length}`; } };
  const repo = createEmailRepository(dbPath);
  const at = new Date("2026-09-25T10:00:00Z");
  const input = { recipient: "test@example.invalid", enabled: true, frequency: "daily" as const, sendTime: "08:00", weekday: null, dayOfMonth: null, scope };
  const schedule = saveEmailSchedule(repo,input,undefined,at);
  assert.deepEqual(repo.findSchedule(schedule.id)?.scope, scope);
  const beforeManual = repo.findSchedule(schedule.id)?.nextRunAt;
  await sendManualDigest(repo,adapter,snapshot,input.recipient,scope,at);
  assert.equal(repo.findSchedule(schedule.id)?.nextRunAt,beforeManual);
  assert.equal(repo.logs().filter((log) => log.type === "MANUAL" && log.status === "SENT").length,1);
  const load = async () => snapshot;
  assert.deepEqual(await runDueEmailSchedules(repo,adapter,load,new Date("2026-09-25T11:00:00Z")), { due: 1, sent: 1, failed: 0, skipped: 0 });
  assert.equal(repo.logs().filter((log) => log.type === "AUTOMATIC" && log.status === "SENT").length,1);
  assert.equal(repo.findSchedule(schedule.id)?.lastSentAt !== null,true);
  assert.equal((await runDueEmailSchedules(repo,adapter,load,new Date("2026-09-25T11:00:00Z"))).due,0);
  assert.equal(sent.length,2);
  const persisted = repo.findSchedule(schedule.id)!;
  repo.close();
  const reopened = createEmailRepository(dbPath);
  assert.deepEqual(reopened.findSchedule(schedule.id)?.scope,scope);
  assert.equal(reopened.findSchedule(schedule.id)?.nextRunAt,persisted.nextRunAt);
  setEmailScheduleEnabled(reopened,schedule.id,false,at);
  assert.equal(reopened.findSchedule(schedule.id)?.enabled,false);
  setEmailScheduleEnabled(reopened,schedule.id,true,at);
  assert.equal(reopened.findSchedule(schedule.id)?.enabled,true);
  const failing = saveEmailSchedule(reopened,{ ...input, frequency: "weekly", weekday: 5 },undefined,at);
  const succeeding = saveEmailSchedule(reopened,{ ...input, frequency: "weekly", weekday: 5, scope: emptyPriorityFilters },undefined,at);
  const failAdapter: EmailAdapter = { async send(message) { if (message.idempotencyKey.includes(failing.id)) throw new Error("mock failure"); sent.push(message); return "mock-ok"; } };
  const run = await runDueEmailSchedules(reopened,failAdapter,load,new Date("2026-09-25T11:00:00Z"));
  assert.equal(run.failed,1); assert.equal(run.sent,1);
  assert.equal(reopened.logs().find((log) => log.scheduleId === failing.id)?.status,"FAILED");
  assert.equal(reopened.logs().find((log) => log.scheduleId === succeeding.id)?.status,"SENT");
  reopened.deleteSchedule(failing.id);
  assert.equal(reopened.findSchedule(failing.id),null);
  reopened.close();
  const oldKey = process.env.RESEND_API_KEY, oldFrom = process.env.RESEND_FROM_EMAIL;
  delete process.env.RESEND_API_KEY; delete process.env.RESEND_FROM_EMAIL;
  assert.equal(resendConfigured(),false);
  assert.ok(priorityDigest(snapshot,scope).text.length > 0);
  if (oldKey) process.env.RESEND_API_KEY = oldKey;
  if (oldFrom) process.env.RESEND_FROM_EMAIL = oldFrom;
  assert.equal(JSON.stringify(snapshot.scores),scoresBefore);
  assert.equal(JSON.stringify(snapshot.tiers),tiersBefore);
  console.log("Email PASS: preview, envio manual mockado, recorrência, persistência, scope, idempotência, falha isolada e ausência de credenciais.");
} finally { rmSync(temporary,{ recursive:true, force:true }); }
